### ISSUE TITLE
Wrong results using some own datasets

### ISSUE THREAD

**Issue by aW4KeNiNG** [colmap/glomap#116]
Hi.

I'm trying to use Glomap but it doesn't work with some own datasets. For example, in this one, Colmap works, but Glomap is completely inaccurate.

Colmap:

![image](https://github.com/user-attachments/assets/590f8cd6-448b-4711-b9ba-3061748eec2d)

```
colmap feature_extractor --database_path glomap/database.db --image_path images --ImageReader.single_camera 1 --ImageReader.camera_model PINHOLE --SiftExtraction.use_gpu 1
colmap exhaustive_matcher --database_path glomap/database.db --SiftMatching.use_gpu 1
colmap mapper --database_path colmap/database.db --image_path images --output_path colmap/sparse
```

Glomap:

![image](https://github.com/user-attachments/assets/094d6699-d0b6-4f21-bc8b-86618c717c9e)

```
colmap feature_extractor --database_path glomap/database.db --image_path images --ImageReader.single_camera 1 --ImageReader.camera_model PINHOLE --SiftExtraction.use_gpu 1
colmap exhaustive_matcher --database_path glomap/database.db --SiftMatching.use_gpu 1
glomap mapper --database_path glomap/database.db --image_path images --output_path glomap/sparse
```

I'm using the latest git commit for Colmap and Glomap on Linux. The same happens on Windows. Any help is appreciated.

**Comment by aW4KeNiNG** [comment]
I forgot to include the images, colmap and glomap results.

https://mega.nz/file/P94g1L6B#WFowWZSsncfr8diYsnM1o82y8wNIr_tAV3oREJSmMb8

**Comment by lpanaf** [comment]
Hi @aW4KeNiNG, thanks for providing the dataset so that we can replicate the failure case. It turns out that the initial dataset is quite noisy and contain a lot of outlier edges. I played around with it and found that if you filter it more aggressively, for example, by setting `--Thresholds.min_inlier_num 200` (originally, it is only 30), then you can get the expected result. Hope this can help you in other cases.

**Comment by aW4KeNiNG** [comment]
Thanks! It works now.
