### ISSUE TITLE
Feed glomap output camera positions to colmap global bundle adjustment?

### ISSUE THREAD

**Issue by arcman7** [colmap/glomap#83]
Question - can we feed the output camera positions from glomap to colmap mapper / global bundle adjustment process?

If so, are there any potential pitfalls to doing this?

**Comment by lpanaf** [comment]
Hi, it should be possible to do this by directly calling `colmap bundle_adjuster --input_path INPUT_DIR --output_path OUTPUT_DIR`. However, I am not very sure how much of the benefit you will see from this option, since GLOMAP contains several rounds of bundle adjustment as well.

**Comment by arcman7** [comment]
Yeah - tried that, and you're right. Not much difference, but sometimes it helps a little.

**Comment by elidiot18** [comment]
Does glomap perform bundle adjustment better and faster than colmap, or this step is about the same ? If so, it would be beneficial to have a glomap bundle_adjuster instead of running the colmap one (not for the original purpose of this issue, but for optimising poses from SLAM for instance). Thanks for the guidance !
